"""remove ticket_id

Revision ID: 45748d1ec0da
Revises: 84b4c8595595
Create Date: 2026-09-15 21:38:49.816599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45748d1ec0da'
down_revision: Union[str, Sequence[str], None] = '84b4c8595595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_ticket_id'), table_name='tickets')
    op.drop_column('tickets', 'ticket_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    op.add_column(
        'tickets',
        sa.Column(
            'ticket_id',
            sa.INTEGER(),
            nullable=True
        )
    )

    op.execute(
        sa.text(
            "UPDATE tickets SET ticket_id = id"
        )
    )

    # SQLite não permite alterar facilmente a coluna
    # existente de nullable=True para nullable=False.
    # Portanto, mantemos nullable=True no downgrade.
    
    op.create_index(
        op.f('ix_tickets_ticket_id'),
        'tickets',
        ['ticket_id'],
        unique=True
    )