"""create users tickets and conversation messages

Revision ID: 84b4c8595595
Revises: 
Create Date: 2026-09-14 20:50:43.097210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '84b4c8595595'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('customer_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('customer_age', sa.Integer(), nullable=True),
    sa.Column('customer_gender', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('product_purchased', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('date_of_purchase', sa.DateTime(), nullable=True),
    sa.Column('ticket_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('ticket_subject', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('ticket_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ticket_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('ticket_priority', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('ticket_channel', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('first_response_time', sa.DateTime(), nullable=True),
    sa.Column('time_to_resolution', sa.DateTime(), nullable=True),
    sa.Column('resolution', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_satisfaction_rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_customer_email'), 'tickets', ['customer_email'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_id'), 'tickets', ['ticket_id'], unique=True)
    op.create_index(op.f('ix_tickets_ticket_status'), 'tickets', ['ticket_status'], unique=False)
    op.create_index(op.f('ix_tickets_user_id'), 'tickets', ['user_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_ticket_id'), 'conversation_messages', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_messages_ticket_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_tickets_user_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_ticket_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_ticket_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_customer_email'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
